(ns scriptore.data)

;; Forgive me weird formatting although that
;; facilitates text operations for good...

(def shorters {
"Rdz" :historical
"Wj" :historical
"Kpł" :historical
"Lb" :historical
"Pwt" :historical
"Joz" :historical
"Sdz" :historical
"Rt" :historical
"1Sm" :historical
"2Sm" :historical
"1Krl" :historical
"2Krl" :historical
"1Krn" :historical
"2Krn" :historical
"Ezd" :historical
"Ne" :historical
"Tb" :historical
"Jdt" :historical
"Est" :historical
"1Mch" :historical
"2Mch" :historical
"Hi" :historical
"Ps" :historical
"Prz" :historical
"Koh" :historical
"Pnp" :historical
"Mdr" :historical
"Syr" :historical
"Iz" :prophetic
"Jr" :prophetic
"Lm" :prophetic
"Ba" :prophetic
"Ez" :prophetic
"Dn" :prophetic
"Oz" :prophetic
"Jl" :prophetic
"Am" :prophetic
"Ab" :prophetic
"Jon" :prophetic
"Mi" :prophetic
"Na" :prophetic
"Ha" :prophetic
"So" :prophetic
"Ag" :prophetic
"Za" :prophetic
"Ml" :prophetic
"Mt" :evangelic
"Mk" :evangelic
"Łk" :evangelic
"J" :evangelic
"Dz" :non-evangelic
"Rz" :non-evangelic
"1Kor" :non-evangelic
"2Kor" :non-evangelic
"Ga" :non-evangelic
"Ef" :non-evangelic
"Flp" :non-evangelic
"Kol" :non-evangelic
"1Tes" :non-evangelic
"2Tes" :non-evangelic
"1Tm" :non-evangelic
"2Tm" :non-evangelic
"Tt" :non-evangelic
"Flm" :non-evangelic
"Hbr" :non-evangelic
"Jk" :non-evangelic
"1P" :non-evangelic
"2P" :non-evangelic
"1J" :non-evangelic
"2J" :non-evangelic
"3J" :non-evangelic
"Jud" :non-evangelic
"Ap" :non-evangelic
})
